server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xzshop?useSSL=false&serverTimeZone=UTC
    username: enjuppa
    password: 287452WTsl
    driver-class-name: com.mysql.jdbc.Driver

  main:
    allow-circular-references: true


##映射文件
#mybatis:
  mapper-locations: classpath:mapper/*.xml